/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Trujirendjj
 */
public class SimuladorUI extends javax.swing.JFrame {

    /**
     * Creates new form SimuladorUI
     */
    public SimuladorUI() {
        initComponents();
        this.errorPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        frenarButton = new javax.swing.JLabel();
        frenarBruscamenteButton = new javax.swing.JLabel();
        acelerarButton = new javax.swing.JLabel();
        encenderButton = new javax.swing.JLabel();
        apagarButton = new javax.swing.JLabel();
        errorPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        errorText = new javax.swing.JLabel();
        velocidad = new javax.swing.JLabel();
        labelVelocidad = new javax.swing.JLabel();
        interiorCarro = new javax.swing.JLabel();
        pistaImagen = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombreLlantasLabel = new javax.swing.JLabel();
        velLlantasLabel = new javax.swing.JLabel();
        nombreMotorLabel = new javax.swing.JLabel();
        velMotorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1316, 500));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frenarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frenarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1593815.png"))); // NOI18N
        frenarButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(frenarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 110, -1));

        frenarBruscamenteButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frenarBruscamenteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/3410140.png"))); // NOI18N
        frenarBruscamenteButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(frenarBruscamenteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 110, 100));

        acelerarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acelerarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/16013421.png"))); // NOI18N
        acelerarButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(acelerarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 110, 140));

        encenderButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encenderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/4943215.png"))); // NOI18N
        jPanel1.add(encenderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 120));

        apagarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apagarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/9068977.png"))); // NOI18N
        apagarButton.setToolTipText("");
        jPanel1.add(apagarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 100, 100));

        errorPanel.setBackground(new java.awt.Color(255, 255, 255));
        errorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/simulation/error.png"))); // NOI18N
        errorPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 50, 50));

        errorText.setBackground(new java.awt.Color(255, 0, 0));
        errorText.setFont(new java.awt.Font("ROG Fonts", 0, 10)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 0, 0));
        errorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorText.setText("jLabel5");
        errorPanel.add(errorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 640, 30));

        jPanel1.add(errorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 700, 50));

        velocidad.setBackground(new java.awt.Color(255, 0, 0));
        velocidad.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        velocidad.setForeground(new java.awt.Color(0, 0, 255));
        velocidad.setText("VELOCIDAD:");
        jPanel1.add(velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        labelVelocidad.setBackground(new java.awt.Color(255, 0, 0));
        labelVelocidad.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        labelVelocidad.setForeground(new java.awt.Color(0, 0, 255));
        labelVelocidad.setText("VELOCIDAD");
        jPanel1.add(labelVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 310, 30));

        interiorCarro.setBackground(new java.awt.Color(0, 0, 0));
        interiorCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/simulation/interior.png"))); // NOI18N
        jPanel1.add(interiorCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 490));

        pistaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/simulation/track_image/yasmarina.jpg"))); // NOI18N
        jPanel1.add(pistaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 490));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MOTOR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("VELOCIDAD SOPORTADA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/2422850.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1820663.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 130, 130));

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LLANTAS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("NOMBRE");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("NOMBRE");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("VELOCIDAD MAXIMA");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 380, -1, -1));

        nombreLlantasLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        nombreLlantasLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLlantasLabel.setText("NOMBRE");
        jPanel1.add(nombreLlantasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 150, -1, -1));

        velLlantasLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        velLlantasLabel.setForeground(new java.awt.Color(255, 255, 255));
        velLlantasLabel.setText("VELOCIDAD SOPORTADA");
        jPanel1.add(velLlantasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, -1, -1));

        nombreMotorLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        nombreMotorLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreMotorLabel.setText("NOMBRE");
        jPanel1.add(nombreMotorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 350, -1, -1));

        velMotorLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        velMotorLabel.setForeground(new java.awt.Color(255, 255, 255));
        velMotorLabel.setText("VELOCIDAD MAXIMA");
        jPanel1.add(velMotorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getAcelerarButton() {
        return acelerarButton;
    }
    
    public JLabel getApagarButton() {
        return apagarButton;
    }
    
    public JLabel getEncenderButton() {
        return encenderButton;
    }
    
    public JLabel getFrenarBruscamenteButton() {
        return frenarBruscamenteButton;
    }
    
    public JLabel getFrenarButton() {
        return frenarButton;
    }
    public void addAcelerarButtonListener(java.awt.event.MouseListener l) {
        this.acelerarButton.addMouseListener(l);
    }

    public void addApagarButtonListener(java.awt.event.MouseListener l) {
        this.apagarButton.addMouseListener(l);
    }

    public void addEncenderButtonListener(java.awt.event.MouseListener l) {
        this.encenderButton.addMouseListener(l);
        
    }

    public JLabel getErrorText() {
        return errorText;
    }
    
    public JPanel getErrorPanel() {
        return errorPanel;
    }

    public JLabel getPistaImagen() {
        return pistaImagen;
    }
    
    public void addFrenarBruscamenteButtonListener(java.awt.event.MouseListener l) {
        this.frenarBruscamenteButton.addMouseListener(l);
    }

    public void addFrenarButtonListener(java.awt.event.MouseListener l) {
        this.frenarButton.addMouseListener(l);
    }

    public JLabel getLabelVelocidad() {
        return labelVelocidad;
    }

    public JLabel getNombreLlantasLabel() {
        return nombreLlantasLabel;
    }

    public JLabel getNombreMotorLabel() {
        return nombreMotorLabel;
    }

    public JLabel getVelLlantasLabel() {
        return velLlantasLabel;
    }

    public JLabel getVelMotorLabel() {
        return velMotorLabel;
    }
    
    public void createForm(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acelerarButton;
    private javax.swing.JLabel apagarButton;
    private javax.swing.JLabel encenderButton;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JLabel errorText;
    private javax.swing.JLabel frenarBruscamenteButton;
    private javax.swing.JLabel frenarButton;
    private javax.swing.JLabel interiorCarro;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelVelocidad;
    private javax.swing.JLabel nombreLlantasLabel;
    private javax.swing.JLabel nombreMotorLabel;
    private javax.swing.JLabel pistaImagen;
    private javax.swing.JLabel velLlantasLabel;
    private javax.swing.JLabel velMotorLabel;
    private javax.swing.JLabel velocidad;
    // End of variables declaration//GEN-END:variables
}
